const data = {
  products: [
    {
      name: 'Ceai negru',
      slug: 'ceai-negru',
      category: 'Ceai',
      image: '/images/p1.jpg',
      price: 17,
      countInStock: 10,
      brand: 'Sonnentor',
      rating: 4.5,
      numReviews: 10,
      description: 'Produs de inalta calitate',
    },
    {
      name: 'Ulei esential arbore de ceai',
      slug: 'ulei-esential-arbore-de-ceai',
      category: 'Ulei',
      image: '/images/p2.jpg',
      price: 32,
      countInStock: 0,
      brand: 'Arom Science',
      rating: 4.5,
      numReviews: 10,
      description: 'Produs de inalta calitate',
    },
    {
      name: 'Sirop vitamine',
      slug: 'sirop-vitamine',
      category: 'Sirop',
      image: '/images/p3.jpg',
      price: 35,
      countInStock: 10,
      brand: 'PlantExtrakt',
      rating: 4.5,
      numReviews: 10,
      description: 'Produs de inalta calitate',
    },
    {
      name: 'Lecitina forte',
      slug: 'lecitina-forte',
      category: 'Suplimente',
      image: '/images/p4.jpg',
      price: 13,
      countInStock: 7,
      brand: 'Parapharm',
      rating: 4.5,
      numReviews: 10,
      description: 'Produs de inalta calitate',
    },
  ],
};

export default data;
